name: Deploy M3U File to Codeberg

on:
  push:
    branches:
      - master  # 只监听master分支上的提交
  workflow_dispatch:  # 手动触发选项


jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      env:
        CODEBERG_PRIVATE_KEY: ${{ secrets.CODEBERG_PRIVATE_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        mkdir -p ~/.ssh  # 确保 .ssh 目录存在
        echo "$CODEBERG_PRIVATE_KEY" | tr -d '\r' | tee ~/.ssh/id_rsa > /dev/null
        chmod 600 ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa  # 调试信息：打印密钥内容
        ssh-add ~/.ssh/id_rsa

    - name: Add Codeberg SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa codeberg.org >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Clone Codeberg repository
      run: |
        git clone git@codeberg.org:kyeo/iptv-m3u.git codeberg-repo
        cd codeberg-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Copy specific file
      run: |
        if [ -f "output/result.m3u" ]; then
          cp output/result.m3u codeberg-repo/
        else
          echo "File output/result.m3u does not exist."
          exit 1
        fi
        
    - name: Commit and push to Codeberg
      run: |
        cd codeberg-repo
        git add result.m3u
        git commit -m "Update result.m3u from GitHub Actions"
        git push origin main
