name: Deploy M3U File to GIT_KYEO_TOP

on:
  push:
    branches:
      - master  # 只监听master分支上的提交
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:  # 手动触发选项


jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone iptv box repository
      run: |
        git clone https://${{ secrets.GIT_PRIVATE_KEY }}@git.kyeo.top/kyeo/box.git box
        cd box
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Copy specific file
      run: |
        if [ -f "output/result.m3u" ]; then
          cp output/result.m3u box/iptv.m3u
        else
          echo "File output/result.m3u does not exist."
          exit 1
        fi
        
    - name: Commit and push to git.kyeo.top
      run: |
        cd box
        git add iptv.m3u
        git commit -m "Update iptv.m3u from GitHub Actions"
        git push origin main
        
    - name: Send Notification to Gotify
      if: always() # 确保无论作业成功还是失败都会执行此步骤
      run: |
        curl -X POST "$GOTIFY_SERVER/message?token=$GOTIFY_TOKEN" \
             -F "title=GitHub Action: ${{ github.workflow }}" \
             -F "priority=5" \
             -F "message=推送M3U到git.kyeo.top: ${{ job.status }}"
      env:
        GOTIFY_SERVER: ${{ secrets.GOTIFY_SERVER }}
        GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
