name: Deploy M3U File to Codeberg

on:
  push:
    branches:
      - master  # 只监听master分支上的提交
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:  # 手动触发选项


jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      env:
        GIT_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        mkdir -p ~/.ssh  # 确保 .ssh 目录存在
        echo "$GIT_PRIVATE_KEY" | tr -d '\r' | tee ~/.ssh/id_rsa > /dev/null
        chmod 600 ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa  # 调试信息：打印密钥内容
        ssh-add ~/.ssh/id_rsa

    - name: Add Codeberg SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa git.kyeo.top >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Clone iptv box repository
      run: |
        git clone git@git.kyeo.top:2222/kyeo/box.git box
        cd box
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Copy specific file
      run: |
        if [ -f "output/result.m3u" ]; then
          cp output/result.m3u box/iptv.m3u
        else
          echo "File output/result.m3u does not exist."
          exit 1
        fi
        
    - name: Commit and push to git.kyeo.top
      run: |
        cd box
        git add iptv.m3u
        git commit -m "Update iptv.m3u from GitHub Actions"
        git push origin main
        
    - name: Send Notification to Gotify
      if: always() # 确保无论作业成功还是失败都会执行此步骤
      run: |
        curl -X POST "$GOTIFY_SERVER/message?token=$GOTIFY_TOKEN" \
             -F "title=GitHub Action: ${{ github.workflow }}" \
             -F "priority=5" \
             -F "message=推送M3U到git.kyeo.top: ${{ job.status }}"
      env:
        GOTIFY_SERVER: ${{ secrets.GOTIFY_SERVER }}
        GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
